In [1]:
#Exercice1
import numpy as np
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#Exercice2
import numpy as np 
array_int = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
print(array_int)

[3 2 0 1 2]


In [3]:
#Exercice3
import numpy as np
array_1d =np.array([[ 1, 2, 3 ], [ 4, 5, 6 ], [ 7, 8, 9 ]])
print(array_1d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Exercice4
import numpy as np
tableau_aleatoire = np.random.rand(4, 5)
print(tableau_aleatoire)

[[0.35635709 0.49838963 0.88552148 0.12485742 0.7360565 ]
 [0.99487131 0.22084033 0.31868224 0.10107959 0.47152769]
 [0.6247894  0.76979523 0.15947705 0.19641414 0.54369997]
 [0.09737382 0.97969431 0.84135442 0.87932551 0.41222169]]


In [5]:
#Exercice5
import numpy as np
array_2d = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print("Second row:", array_2d[1, :])

Second row: [20 21 22 23 24]


In [6]:
#Exercice6
import numpy as np
mon_tableau = np.arange(10)
tableau_inverse = mon_tableau[::-1] #notion de [début : fin : pas]

print(tableau_inverse)

[9 8 7 6 5 4 3 2 1 0]


In [7]:
#Exercice7
import numpy as np
matrice_id = np.identity(4)
print(matrice_id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Exercice8
import numpy as np

mon_tableau = np.arange(10)
somme = np.sum(mon_tableau)
moyenne = np.mean(mon_tableau)

print(f"Sum: {somme}, Average: {moyenne}")

In [3]:
#Exercice9
import numpy as np
mon_tableau = np.arange(1,21)
result = mon_tableau.reshape(4,5)
print (result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [2]:
#Exercice10
import numpy as np

mon_tableau = np.arange(10)
nombres_impairs = mon_tableau[mon_tableau % 2 != 0]

print(nombres_impairs)

[1 3 5 7 9]
